### ISSUE TITLE
I can't resize my pear

### ISSUE THREAD

**Issue by lorenzosquadrani** [lorenzosquadrani/RobertasTree#5]
The pear in the README is a symbol representing all RobertasTree is founded on. 

Unfortunately, github ignores all attributes that I try to use to format the image (:width:, :class:). After some googling, it seems like this is a github unsolved issue. If someone can find the solution, I'll always be grateful :heavy_dollar_sign: !

**Comment by malloc0x3cc** [comment]
The only workaround I know of is actually not using `.. image::` but `.. raw:: html` instead.
#6

**Comment by lorenzosquadrani** [comment]
Simple and effective. Thank you!
